### ISSUE TITLE
Theme compatibility

### ISSUE THREAD

**Issue by Dschogo** [yourselvs/RoleFilter#1]
Hey awesome plugin, found some incompatibilities with skins as seen in attachement. (im using ClearVision)

Without any theme applied it works fine.

![image](https://user-images.githubusercontent.com/36862419/144117546-5b4c9af6-aea2-462e-9ac0-a2546ebf7b0d.png)

Tried to fix it myself with some css, idnt work out. Sometimes just refhresing css fixed it (disable and enable a random css property in debugger belonging to that container)

**Comment by yourselvs** [comment]
Hey there, I'm aware of this issue, I don't use themes so I haven't gotten around to it yet
